version: "2.9"

services:

  postgres:
    image: postgres:15.2
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lab_work_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lab_work_db
      - POSTGRES_PORT=5432
    ports:
      - "5433:5432"
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
      - "127.0.0.11"
    expose:
      - 5433
    networks:
      - default_network

  migrate:
    container_name: 'migrate'
    build: ./src
    command: >
      /bin/sh -c "python3 manage.py makemigrations --force-color --no-input -v 3
      && python3 manage.py makemigrations --merge --no-input -v 3
      && python3 manage.py migrate --force-color -v 3
      && python3 manage.py createsuperuser --noinput; exit 0"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@mail.com
    depends_on:
      postgres:
        condition: service_started
    networks:
      - default_network

  api:
    image: labprofi-lab2-migrate
    command: python runserver.py
    volumes:
      - ./src:/backend_root
    ports:
      - "8080:8080"
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
      - "127.0.0.11"
    depends_on:
      - migrate
    networks:
      - default_network

networks:
  default_network:

